#!/bin/sh

./configure --prefix=/srv/devel/sandbox/ \
    --disable-static \
    --enable-shared \
    --enable-gtk-doc=yes \
    --enable-xlib=yes \
    --enable-xlib-xrender=no \
    --enable-xcb=no \
    --enable-qt=no \
    --enable-fc=no \
    --enable-minigui=yes \
    --enable-drm=yes \
    --enable-gl=yes \
    --enable-egl=yes
