#!/bin/sh

./configure \
    --disable-static \
    --enable-shared \
    --enable-xlib=no \
    --enable-xlib-xrender=no \
    --enable-xcb=no \
    --enable-qt=no \
    --enable-fc=no \
    --enable-minigui=yes \
    --enable-drm=yes \
    --enable-gl=yes \
    --enable-egl=yes
